# Dockerfile — Testes da linguagem EV
FROM python:3

WORKDIR /app

# Copia os arquivos da atv08 para o container
COPY . .

# Comando padrão roda os testes de lexer e parser
CMD ["python3", "testes.py"]
